### ISSUE TITLE
Android build Error

### ISSUE THREAD

**Issue by KS-Balaji** [mariodev12/react-native-netflix#4]
Hi,
 I am trying to take android build in windows system. I got the following error .how to fix it.
![screenshot_2017-09-01-12-15-31-724 1](https://user-images.githubusercontent.com/31532406/29958638-579f19a2-8f11-11e7-926f-2f4ec35f9d17.jpeg)

**Comment by masad83** [comment]
I have same issue, any update about this please..

**Comment by masad83** [comment]
issue fixed.
just make index.android.js same as index.ios.js
so the code inside index.android.js  will be like this 

import { AppRegistry } from 'react-native';
import IndexApp from './src/'
AppRegistry.registerComponent('NetflixApp', () => IndexApp);
